version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ShinchokuNote
      - .bundle_install:/ShinchokuNote/vendor/bundle:cached
    ports:
      - "3000:3000"
    links:
      - db_dev
      - db_test
  db_dev:
    image: postgres:10.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=shinchokunote_development"
  db_test:
    image: postgres:10.1
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=shinchokunote_test"
