version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/development/app/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/ShinchokuNote:cached
      - bundle:/ShinchokuNote/vendor/bundle
      - node_modules:/ShinchokuNote/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
    links:
      - db_dev
      - db_test
  db_dev:
    image: postgres:10.1
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=shinchokunote_development"
  db_test:
    image: postgres:10.1
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=shinchokunote_test"

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  yarn_cache:
    driver: local
  dbdata:
    driver: local
