version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ShinchokuNote
      - .bundle_install:/ShinchokuNote/vendor/bundle:cached
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY:
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./public:/var/www/static_files
      - ./nginx/http_config.erb:/var/lib/nginx-conf/beta.shinchoku.net.conf.erb:ro
      - ./nginx/https_config.erb:/var/lib/nginx-conf/beta.shinchoku.net.ssl.conf.erb:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
      - jenkins
    restart: always
    environment:
      DOMAINS: 'beta.shinchoku.net -> http://app:3000'
      # FORCE_RENEW: 'true' # テスト用。STAGE: productionの場合は切る
      # STAGE: 'production'
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: '--prefix=/jenkins'
    volumes:
      - .jenkins:/var/jenkins_home
