version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/ShinchokuNote
    docker: 
      - image: circleci/ruby:2.6.1
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # apt setup
      - run: sudo apt update
      - run: sudo apt upgrade

      # Dependencies installation
      - type: shell
        command: |
          sudo apt install libsodium-dev

      # Restore bundle cache
      - restore_cache:
          key: rails-dependencies-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --without production --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bin/rails db:create
      - run: bin/rails db:schema:load

      # Assets precompile
      - run: DISABLE_SPRING=true bin/rake assets:precompile

      # Run rspec in parallel
      - type: shell
        command: |
          DISABLE_SPRING=true bin/rails test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
