openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: main api
  contact: {}
  termsOfService: 'https://shinchoku.net'
servers:
  - url: 'http://localhost:3000'
    description: development
  - url: 'https://shinchoku.net'
    description: production
paths:
  '/notes/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  name:
                    type: string
                  desc:
                    type: string
                  stage:
                    type: string
                  view_stance:
                    type: string
                  rating:
                    type: string
                  watchers_count:
                    type: integer
                  shinchoku_dodeskas_count:
                    type: integer
                  comments_count:
                    type: integer
                  created_at:
                    type: string
              examples: {}
      operationId: get-note
      description: Get note information
components:
  schemas:
    User:
      title: USer
      type: object
      properties:
        id:
          type: string
    Note:
      title: Note
      type: object
      properties:
        type:
          type: string
        name:
          type: string
        desc:
          type: string
        url:
          type: string
        watch_url:
          type: string
        stage:
          type: string
        view_stance:
          type: string
        rating:
          type: string
        watchers_count:
          type: integer
  securitySchemes: {}
