default: &default
  twitter:
    key: twitter_key_dummy
    secret: twitter_secret_dummy

  twitter_test_fixture:
    okaka_token: okaka_token_dummy
    okaka_secret: okaka_secret_dummy
    noritama_token: noritama_token_dummy
    noritama_secret: noritama_secret_dummy
    noriwasa_token: noriwasa_secret_dummy
    noriwasa_secret: noriwasa_secret_dummy
  
  vapid:
    public_key: vapid_public_key_dummy
    private_key: vapid_private_key_dummy

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default