apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    
    http{
      server{
        listen 80;
          
        # Rooting for /public
        location / {
          root /var/www/static_files;
          try_files $uri @rails;
        }

        # Rooting for rails
        location @rails {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }