apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: rails
  type: NodePort
  selector:
    app: rails
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  selector:
    matchLabels:
      app: rails
  replicas: 1
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: furikake6000/shinchokunote:kube_test
        ports:
        - containerPort: 3000
        args: 
          - /bin/sh
          - -c
          - "bundle exec rails s -p 3000 -b '0.0.0.0'"
        env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails
                key: secret-key-base
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: cloudsql
                key: host
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql
                key: password
